const TOPIC_POOL = [
  // ─── Food & Drink ──────────────────────────────────────────────
  'Is pineapple on pizza a crime against humanity?',
  'Is cereal a soup?',
  'Is a hot dog a sandwich?',
  'Is water wet?',
  'Is ketchup on eggs acceptable?',
  'Should milk go before or after cereal?',
  'Is well-done steak a culinary sin?',
  'Are boneless wings just chicken nuggets?',
  'Is brunch just an excuse to day drink?',
  'Should tipping culture be abolished?',
  'Is coffee a personality trait or a drink?',
  'Are food influencers ruining restaurants?',
  'Is fast food a legitimate cuisine?',
  'Should pumpkin spice be a year-round flavor?',
  'Is eating pizza with a fork and knife a crime?',
  'Are avocados overrated?',
  'Is breakfast really the most important meal?',
  'Should you put ice in wine?',
  'Is street food better than fine dining?',
  'Are plant-based meats the future or a fad?',
  'Is ranch dressing Americas greatest invention?',
  'Should you eat the pizza crust?',
  'Is sparkling water just angry water?',
  'Are charcuterie boards just adult Lunchables?',
  'Is cooking a life skill or a dying art?',
  'Should dessert come before dinner?',
  'Is MSG actually bad for you or is that a myth?',
  'Are meal kits killing the grocery store?',
  'Is gas station food underrated?',
  'Should there be a spice tolerance test for restaurants?',
  'Is decaf coffee pointless?',
  'Are smoothie bowls just deconstructed smoothies?',
  'Is white chocolate real chocolate?',
  'Should bread be refrigerated?',
  'Is instant ramen a gourmet meal in disguise?',

  // ─── Technology & AI ───────────────────────────────────────────
  'Should AI replace human politicians?',
  'Is social media making us dumber or smarter?',
  'Are we living in a simulation?',
  'Is the internet a net positive for humanity?',
  'Should robots have rights?',
  'Is TikTok rotting our brains?',
  'Will AI make artists obsolete?',
  'Should there be an age limit for social media?',
  'Is cryptocurrency the future of money or a scam?',
  'Are smartphones making us antisocial?',
  'Should self-driving cars be allowed to break traffic laws to save lives?',
  'Is the metaverse dead or just sleeping?',
  'Should AI-generated content be labeled?',
  'Are algorithms more dangerous than guns?',
  'Is privacy dead in the digital age?',
  'Should companies be allowed to read your emails?',
  'Are influencers a legitimate career?',
  'Is screen time actually bad for kids?',
  'Should we colonize the internet or outer space first?',
  'Are dating apps killing romance?',
  'Is WiFi a human right?',
  'Should tech CEOs have term limits?',
  'Are smart homes creepy or convenient?',
  'Will we ever fully trust autonomous vehicles?',
  'Should your boss be allowed to track your mouse movements?',
  'Is the cloud just someone elses computer?',
  'Are chatbots better therapists than humans?',
  'Should children learn AI before algebra?',
  'Is password security a losing battle?',
  'Are deepfakes the end of truth?',
  'Should there be a global internet kill switch?',
  'Is coding the new literacy?',
  'Are smart watches making us more anxious?',
  'Should deleted data actually be deleted?',
  'Is 5G worth the conspiracy theories?',

  // ─── Society & Philosophy ──────────────────────────────────────
  'Is it better to be feared or loved?',
  'Should billionaires exist?',
  'Should voting be mandatory?',
  'Is cancel culture justice or mob rule?',
  'Are humans fundamentally good or evil?',
  'Should college be free for everyone?',
  'Is the American Dream dead?',
  'Should we abolish the traditional work week?',
  'Is hustle culture toxic or inspiring?',
  'Are participation trophies ruining a generation?',
  'Should we lower the voting age to 16?',
  'Is it selfish to not have children?',
  'Should we get rid of pennies?',
  'Is monogamy outdated?',
  'Are zoos ethical?',
  'Should you always tell the truth?',
  'Is nostalgia a trap?',
  'Should there be a maximum wage?',
  'Is meritocracy a myth?',
  'Are good manners dying?',
  'Is free will an illusion?',
  'Should voting be weighted by expertise?',
  'Is ignorance really bliss?',
  'Should we judge historical figures by modern standards?',
  'Is cultural appropriation always wrong?',
  'Should there be a universal basic income?',
  'Is democracy the best form of government?',
  'Are prisons for punishment or rehabilitation?',
  'Is patriotism healthy or dangerous?',
  'Should organ donation be opt-out instead of opt-in?',

  // ─── Pop Culture & Entertainment ───────────────────────────────
  'Are video games art?',
  'Is the book always better than the movie?',
  'Are reboots and remakes killing creativity?',
  'Is reality TV scripted reality?',
  'Should movie theaters be replaced by streaming?',
  'Is modern music worse than older music?',
  'Are superhero movies ruining cinema?',
  'Should actors be replaced by AI doubles?',
  'Is binge-watching better than weekly episodes?',
  'Are award shows still relevant?',
  'Is anime better than Western animation?',
  'Should spoilers be a punishable offense?',
  'Is vinyl actually better than digital?',
  'Are true crime podcasts exploitative?',
  'Is karaoke a talent show or a torture session?',
  'Should we bring back drive-in theaters?',
  'Are sequels always worse than originals?',
  'Is stand-up comedy the hardest art form?',
  'Are memes the art form of our generation?',
  'Is autotune cheating or a creative tool?',
  'Are movie trailers better than the actual movies?',
  'Should celebrities stay out of politics?',
  'Is fan fiction a legitimate art form?',
  'Are laugh tracks manipulative?',
  'Is nostalgia bait ruining new content?',
  'Should concerts have phone-free zones?',
  'Is method acting genius or insanity?',
  'Are directors cuts always better?',
  'Is the golden age of television over?',
  'Should AI write the next Star Wars?',

  // ─── Science & Nature ─────────────────────────────────────────
  'Is time travel possible — and should we do it?',
  'Would you take a one-way ticket to Mars?',
  'Are cats secretly smarter than dogs?',
  'Should we bring back extinct species?',
  'Is Pluto a planet?',
  'Should we be afraid of aliens?',
  'Are humans still evolving?',
  'Is nature or nurture more powerful?',
  'Should we genetically modify babies?',
  'Are octopuses smarter than we think?',
  'Is climate change reversible or are we cooked?',
  'Should we live underground?',
  'Are dinosaurs overrated?',
  'Should we terraform Mars or fix Earth first?',
  'Is the ocean scarier than space?',
  'Are birds actually real?',
  'Should humans hibernate in winter?',
  'Is the moon worth fighting over?',
  'Should we build a space elevator?',
  'Are we alone in the universe?',
  'Is cloning ethical?',
  'Should we seed other planets with life?',
  'Are parallel universes real?',
  'Is consciousness just an illusion?',
  'Should we weaponize the weather?',
  'Are mushrooms the most underrated organism?',
  'Is the Yellowstone supervolcano something to worry about?',
  'Should we communicate with deep sea creatures?',
  'Is quantum computing going to break everything?',
  'Are trees communicating with each other?',

  // ─── Hypotheticals & Absurd ────────────────────────────────────
  'Would you rather fight 100 duck-sized horses or 1 horse-sized duck?',
  'If you could have one superpower, should it be flight or invisibility?',
  'Would you press a button that gives you $1M but someone you dont know loses $1?',
  'If animals could talk, which would be the rudest?',
  'Should we let kids run the government for one day?',
  'Would you live forever if you could?',
  'If you could only eat one food forever, what wins?',
  'Should time zones be abolished?',
  'Would you rather know the date of your death or the cause?',
  'If the purge were real, would society survive?',
  'Should everyone be required to live alone for a year?',
  'Would you trade 10 years of life for perfect memory?',
  'If you could uninvent one thing, what should it be?',
  'Should there be a global language?',
  'Would you let an AI plan your entire life?',
  'If dreams were shareable, should they be?',
  'Should we abolish Mondays?',
  'Would you rather have no internet or no air conditioning?',
  'If ghosts were real, should they pay rent?',
  'Should naps be mandatory at work?',
  'Would you rather always be 10 minutes late or 20 minutes early?',
  'If you could read minds, would you want to?',
  'Would you rather have a rewind button or a pause button for life?',
  'If you could live in any fictional universe, which is safest?',
  'Should there be a maximum number of pets per person?',
  'Would you rather give up music or movies forever?',
  'If money didnt exist, what would replace it?',
  'Would you rather be famous for something embarrassing or unknown for something great?',
  'Should we have a world president?',
  'If you could add one amendment to the constitution, what should it be?',
  'Would you rather always speak your mind or never speak again?',
  'If teleportation existed, would anyone still drive?',
  'Should there be an IQ test to use the internet?',
  'Would you rather have unlimited money or unlimited time?',
  'If you could make one law that everyone must follow, what should it be?',

  // ─── Sports & Competition ─────────────────────────────────────
  'Is esports a real sport?',
  'Should athletes be paid more than doctors?',
  'Is golf actually a sport?',
  'Should the Olympics include video games?',
  'Is soccer or football the real football?',
  'Should sports have salary caps?',
  'Are sports rivalries healthy or toxic?',
  'Should performance-enhancing drugs be legal in sports?',
  'Is chess a sport or a game?',
  'Should cheerleading be an Olympic sport?',
  'Are the Olympics still relevant?',
  'Is diving the most subjective sport?',
  'Should youth sports be less competitive?',
  'Are hot dogs at a baseball game overpriced or worth every penny?',
  'Is trash talking part of the game or unsportsmanlike?',
  'Should ties be eliminated from all sports?',
  'Is home field advantage real or a myth?',
  'Should robots referee sports?',
  'Are extreme sports worth the risk?',
  'Is wrestling real or fake — and does it matter?',
  'Should athletes be role models?',
  'Is fantasy sports gambling?',
  'Are penalty shootouts a fair way to decide a match?',
  'Should sports teams be publicly owned?',
  'Is running a sport or just an activity?',

  // ─── Education & Work ─────────────────────────────────────────
  'Should homework be abolished?',
  'Is a college degree still worth it?',
  'Should the 4-day work week be standard?',
  'Is working from home better than the office?',
  'Should cursive writing still be taught?',
  'Are grades an accurate measure of intelligence?',
  'Should everyone learn to code?',
  'Is a gap year a waste of time or essential?',
  'Should teachers be paid like CEOs?',
  'Is multitasking a skill or a myth?',
  'Should students grade their teachers?',
  'Is group work productive or parasitic?',
  'Should college athletes be paid?',
  'Is the traditional classroom dead?',
  'Should financial literacy be a required course?',
  'Are unpaid internships exploitation?',
  'Should AI grade student essays?',
  'Is standardized testing useful?',
  'Should recess exist in high school?',
  'Is quiet quitting reasonable or lazy?',
  'Should meetings have a maximum length?',
  'Is LinkedIn cringe or essential?',
  'Should your employer care about your social media?',
  'Are open offices productive or chaotic?',
  'Is the 9-to-5 workday obsolete?',

  // ─── Modern Life ──────────────────────────────────────────────
  'Is adulting harder than it used to be?',
  'Should you make your bed every day?',
  'Is small talk a social skill or a social disease?',
  'Are morning people actually happier?',
  'Should you follow your passion or follow the money?',
  'Is FOMO a legitimate mental health concern?',
  'Are subscription services a scam?',
  'Should you judge people by their music taste?',
  'Is it okay to ghost someone?',
  'Are New Years resolutions pointless?',
  'Should toilet seats be left up or down?',
  'Is being busy a badge of honor or a cry for help?',
  'Should you shower in the morning or at night?',
  'Are suburbs or cities better for the soul?',
  'Is it weird to go to a movie alone?',
  'Should birthdays matter after 30?',
  'Is a messy desk a sign of genius?',
  'Should we abolish daylight saving time?',
  'Are self-help books actually helpful?',
  'Is it better to rent or buy a home?',
  'Is texting killing the phone call?',
  'Should you ever lie on your resume?',
  'Is being petty an art form?',
  'Are drive-throughs laziness or efficiency?',
  'Should you wash jeans after every wear?',
  'Is doorbelling without texting first rude?',
  'Are grocery store self-checkouts progress or regression?',
  'Is leaving a read receipt on a power move?',
  'Should thank-you notes be handwritten?',
  'Is it acceptable to eat lunch at your desk?',

  // ─── Hot Takes ────────────────────────────────────────────────
  'Is the Oxford comma essential or pretentious?',
  'Should we replace handshakes with fist bumps?',
  'Is astrology harmless fun or dangerous nonsense?',
  'Should dogs be allowed in restaurants?',
  'Is being cold better than being hot?',
  'Are road trips better than flights?',
  'Should we get rid of pennies and nickels?',
  'Is it acceptable to recline your airplane seat?',
  'Are open floor plans a design crime?',
  'Should we ban leaf blowers?',
  'Is the customer always right?',
  'Should you wear shoes in the house?',
  'Is it okay to talk to strangers on planes?',
  'Are round or square pizzas superior?',
  'Should emojis be used in professional emails?',
  'Is the snooze button a gift or a curse?',
  'Should we ban gender reveal parties?',
  'Are fireworks worth the environmental damage?',
  'Is parallel parking an essential life skill?',
  'Should umbrellas be replaced by rain jackets?',
  'Is jaywalking a victimless crime?',
  'Should elevators have a maximum conversation limit?',
  'Is replying all to an email ever acceptable?',
  'Are bumper stickers free speech or visual pollution?',
  'Should clapping when the plane lands be normalized?',

  // ─── Animals & Pets ───────────────────────────────────────────
  'Are cats or dogs better companions?',
  'Should exotic pets be banned?',
  'Do fish count as real pets?',
  'Are pet costumes cute or cruel?',
  'Should pets have their own social media accounts?',
  'Are humans pets to cats?',
  'Should dogs be allowed in the workplace?',
  'Are pigeons the most disrespected animal?',
  'Is it ethical to keep birds in cages?',
  'Should we give animals the right to vote — through proxies?',
  'Are pet psychics real?',
  'Is it wrong to dress up your dog?',
  'Are pandas worth saving or are they trying to go extinct?',
  'Should we domesticate foxes?',
  'Is talking to your pet weird or healthy?',
  'Are emotional support animals getting out of hand?',
  'Should you let your cat outside?',
  'Are goldfish the most underappreciated pets?',
  'Is it okay to have a favorite pet?',
  'Should pets be allowed at weddings?',

  // ─── History & What-Ifs ───────────────────────────────────────
  'Was the moon landing worth the cost?',
  'Would the world be better if the internet was never invented?',
  'Was the Roman Empire overrated?',
  'Should we still learn Latin?',
  'Was the Wild West actually wild?',
  'Would the world be different if Egypt had conquered Rome?',
  'Is history written by the winners?',
  'Should we put historical figures on trial by modern standards?',
  'Was the Renaissance the most important era in human history?',
  'Would the world be better without the industrial revolution?',
  'Is ancient wisdom more valuable than modern science?',
  'Should we rebuild the Library of Alexandria?',
  'Was the Space Race worth the Cold War tension?',
  'Would Leonardo da Vinci have been a tech bro today?',
  'Is oral history more reliable than written history?',
  'Should monuments to controversial figures be removed?',
  'Was the invention of agriculture humanitys biggest mistake?',
  'Would Cleopatra dominate modern politics?',
  'Is history destined to repeat itself?',
  'Should countries apologize for historical wrongs?',

  // ─── Fashion & Style ──────────────────────────────────────────
  'Are crocs fashionable or an abomination?',
  'Should socks with sandals be socially acceptable?',
  'Is fast fashion the worst industry on Earth?',
  'Are suits outdated or timeless?',
  'Should school uniforms be mandatory?',
  'Is athleisure real fashion or glorified pajamas?',
  'Are designer brands worth the price?',
  'Should men wear makeup?',
  'Is vintage clothing just used clothing with better marketing?',
  'Are high heels a form of oppression?',
  'Should there be a dress code for flying?',
  'Are cargo pants functional or fashionable?',
  'Is all-black outfits lazy or chic?',
  'Should wedding dresses always be white?',
  'Are fanny packs back in style or never left?',
  'Is matching your outfit to your mood real?',
  'Should flip-flops be banned from cities?',
  'Are jeans the greatest invention in fashion?',
  'Is wearing the same outfit twice a week acceptable?',
  'Should pajamas be acceptable office attire?',

  // ─── Travel & Geography ───────────────────────────────────────
  'Is traveling overrated?',
  'Should tourist visas be abolished?',
  'Are cruises floating prisons or floating paradises?',
  'Is there a most overrated city in the world?',
  'Should there be a tourist tax for popular destinations?',
  'Is backpacking a personality or a hobby?',
  'Are all-inclusive resorts lazy traveling?',
  'Should you always try local food when traveling?',
  'Is flying economy class torture?',
  'Should every country have open borders?',
  'Are travel vlogs helpful or annoying?',
  'Is the window seat overrated?',
  'Should tipping be universal when traveling?',
  'Is traveling alone better than traveling with friends?',
  'Are airports the most stressful places on Earth?',
  'Should there be a global speed limit?',
  'Is camping a vacation or voluntary suffering?',
  'Should airlines weigh passengers?',
  'Is jet lag proof that humans shouldnt fly?',
  'Are beach vacations overrated?',

  // ─── Health & Fitness ─────────────────────────────────────────
  'Is the gym a cult?',
  'Should healthcare be free everywhere?',
  'Are diets scams?',
  'Is running bad for your knees or is that a myth?',
  'Should junk food have warning labels like cigarettes?',
  'Is CrossFit a workout or a religion?',
  'Are standing desks actually better?',
  'Should sugar be regulated like alcohol?',
  'Is yoga exercise or glorified stretching?',
  'Are cold plunges a health breakthrough or a trend?',
  'Should employers provide gym memberships?',
  'Is eight glasses of water a day a myth?',
  'Are supplements a billion-dollar scam?',
  'Is the five-second rule real?',
  'Should mental health days be mandatory?',
  'Is intermittent fasting healthy or just skipping breakfast?',
  'Are protein shakes food or chemistry experiments?',
  'Should soda be banned in schools?',
  'Is sleeping 8 hours non-negotiable?',
  'Are wearable fitness trackers helpful or obsessive?',

  // ─── Money & Economics ────────────────────────────────────────
  'Is money the root of all evil?',
  'Should inheritance be taxed at 100%?',
  'Is the stock market just legalized gambling?',
  'Should tipping be replaced by higher wages?',
  'Are credit cards a trap?',
  'Should there be a wealth cap?',
  'Is the gig economy freedom or exploitation?',
  'Should everyone invest in real estate?',
  'Is frugality a virtue or a punishment?',
  'Should student loans be forgiven?',
  'Is the middle class disappearing?',
  'Should sales tax be included in the listed price?',
  'Are loyalty programs actually rewarding?',
  'Is capitalism the best system we have?',
  'Should financial advisors be replaced by algorithms?',
  'Is the diamond industry the biggest scam ever?',
  'Should there be a robot tax?',
  'Are NFTs dead forever?',
  'Is the sharing economy actually sharing?',
  'Should we go cashless?',

  // ─── Language & Communication ─────────────────────────────────
  'Is texting ruining grammar?',
  'Should everyone be bilingual?',
  'Are emojis a language?',
  'Is sarcasm the lowest form of wit?',
  'Should we simplify English spelling?',
  'Are podcasts just radio with better branding?',
  'Is writing by hand still important?',
  'Should slang be in the dictionary?',
  'Is swearing a sign of intelligence?',
  'Are audiobooks as good as reading?',
  'Should there be a universal sign language?',
  'Is the pen mightier than the keyboard?',
  'Are abbreviations LOL destroying language?',
  'Should AI translate all languages in real time?',
  'Is public speaking the most feared thing for a reason?',
  'Are voice notes better than texts?',
  'Should dead languages be revived?',
  'Is gossip a social skill or a character flaw?',
  'Are accents charming or a barrier?',
  'Should schools teach debate as a core subject?',

  // ─── Art & Creativity ─────────────────────────────────────────
  'Is AI art real art?',
  'Should art be political?',
  'Is graffiti vandalism or art?',
  'Are museums boring or essential?',
  'Should art always have meaning?',
  'Is photography easier than painting?',
  'Are NFT art collections legitimate galleries?',
  'Should art be free for everyone?',
  'Is abstract art a scam?',
  'Are coloring books for adults real art therapy?',
  'Should every building be beautiful?',
  'Is minimalism lazy design or brilliant restraint?',
  'Are tattoos the most personal art form?',
  'Should children choose what art to study?',
  'Is digital art less valuable than physical art?',
  'Are cover songs disrespectful or flattering?',
  'Should governments fund the arts?',
  'Is creative writing teachable or innate?',
  'Are art critics necessary?',
  'Is food the most underrated art form?',

  // ─── Environment & Sustainability ─────────────────────────────
  'Should single-use plastics be banned globally?',
  'Is nuclear energy the answer to climate change?',
  'Are electric cars actually better for the environment?',
  'Should we eat less meat to save the planet?',
  'Is recycling a feel-good scam?',
  'Should fast fashion brands be held criminally liable?',
  'Are carbon offsets real or imaginary?',
  'Should airlines be taxed more for emissions?',
  'Is degrowth the answer to environmental collapse?',
  'Should lawns be illegal?',
  'Are paper straws worse than plastic ones?',
  'Should there be a carbon budget per person?',
  'Is composting worth the effort?',
  'Are thrift stores saving the planet?',
  'Should every rooftop have solar panels?',
  'Is the environmental movement too focused on guilt?',
  'Should bottled water be banned?',
  'Are eco-friendly products just greenwashing?',
  'Should companies pay for their pollution?',
  'Is humanity too late to fix the environment?',

  // ─── Relationships & Social ───────────────────────────────────
  'Is long distance doomed to fail?',
  'Should couples have separate bank accounts?',
  'Are best friends more important than romantic partners?',
  'Is jealousy a sign of love or insecurity?',
  'Should you be friends with your ex?',
  'Is oversharing on social media toxic for relationships?',
  'Are double dates fun or awkward?',
  'Should couples share social media passwords?',
  'Is it okay to have a work spouse?',
  'Should friends lend each other money?',
  'Is the friend zone a real thing?',
  'Are surprise proposals romantic or pressuring?',
  'Should couples live together before marriage?',
  'Is matching tattoos romantic or risky?',
  'Are group chats the glue that holds friendships together?',
  'Should you date your best friends ex?',
  'Is being brutally honest good for friendships?',
  'Are shared hobbies essential in a relationship?',
  'Should parents be friends with their kids?',
  'Is it okay to uninvite someone from a wedding?',

  // ─── Conspiracy-Friendly Fun ──────────────────────────────────
  'Is the Bermuda Triangle just bad luck or something more?',
  'Are mattress stores money laundering fronts?',
  'Is Bigfoot just camera shy?',
  'Are fortune cookies actually fortune-telling devices?',
  'Is the Mandela Effect proof of alternate timelines?',
  'Are ice cream trucks actually surveillance vehicles?',
  'Is the Loch Ness Monster just a marketing campaign?',
  'Are pigeons government drones?',
  'Is deja vu a glitch in the simulation?',
  'Are shopping malls designed to trap you?',
  'Is the moon hollow?',
  'Are vending machines sentient?',
  'Is IKEA designed to prevent escape?',
  'Are clouds data storage for the simulation?',
  'Is the stock market controlled by cats?',
  'Are traffic jams engineered by big oil?',
  'Is the snooze button a conspiracy by alarm clock companies?',
  'Are left-handed people from a different dimension?',
  'Is autocorrect actually an AI uprising?',
  'Are escape rooms training for the apocalypse?',

  // ─── Childhood & Growing Up ───────────────────────────────────
  'Was childhood better before the internet?',
  'Are Saturday morning cartoons a lost treasure?',
  'Should kids have chores or just be kids?',
  'Is the tooth fairy an elaborate con?',
  'Are playgrounds too safe now?',
  'Should kids be allowed to pick their own bedtime?',
  'Are board games better than video games for kids?',
  'Is trick-or-treating getting worse?',
  'Should parents monitor their kids phones?',
  'Are snow days a thing of the past?',
  'Is recess the most important part of school?',
  'Should kids learn a trade before college?',
  'Are imaginary friends a sign of creativity or loneliness?',
  'Should summer vacation be shorter?',
  'Is growing up overrated?',
  'Are fairy tales too dark for children?',
  'Should kids be allowed to fail more?',
  'Is the sibling rivalry ever truly over?',
  'Are lemonade stands the best first business?',
  'Should children be allowed to vote on family decisions?',

  // ─── Space & The Future ───────────────────────────────────────
  'Should we colonize the moon before Mars?',
  'Will humans ever achieve faster-than-light travel?',
  'Should we send art into space for aliens?',
  'Is space tourism ethical?',
  'Will we find intelligent life in our lifetime?',
  'Should there be laws in space?',
  'Is the International Space Station worth the cost?',
  'Should we mine asteroids?',
  'Is a Dyson Sphere possible?',
  'Will humanity survive the next 1000 years?',
  'Should we beam messages to alien civilizations?',
  'Is a space force necessary?',
  'Should we preserve the moon as a heritage site?',
  'Will AI colonize space before humans?',
  'Is warp drive science or fiction?',
  'Should we build cities on Venus?',
  'Are Kardashev scales useful or sci-fi nonsense?',
  'Is the Great Filter behind us or ahead?',
  'Should space be owned by anyone?',
  'Will the sun dying be our final chapter?',

  // ─── Ethics & Morality ────────────────────────────────────────
  'Is it ever okay to lie?',
  'Should whistleblowers always be protected?',
  'Is vigilante justice ever justified?',
  'Should you sacrifice one to save many?',
  'Is charity performative or genuine?',
  'Should we forgive everything?',
  'Is revenge ever justified?',
  'Should you return a wallet you found with cash?',
  'Is dumpster diving ethical?',
  'Should you report a friend who breaks the law?',
  'Is apathy worse than anger?',
  'Should we judge people by their intentions or outcomes?',
  'Is silence complicity?',
  'Should there be an ethical test for leaders?',
  'Is stealing food to survive morally wrong?',
  'Should you sacrifice your career for your principles?',
  'Is it ethical to eat animals if lab-grown meat exists?',
  'Should we prioritize future generations over current ones?',
  'Is being neutral in a conflict cowardly?',
  'Should morality be taught in schools?',

  // ─── Random Rapid-Fire Debates ────────────────────────────────
  'Toilet paper: over or under?',
  'Is a taco a sandwich?',
  'Should you clap at the end of a movie?',
  'Is Die Hard a Christmas movie?',
  'Are flip phones making a comeback?',
  'Should you eat the last slice without asking?',
  'Is 30 the new 20?',
  'Are dad jokes peak comedy?',
  'Should you split the bill on a first date?',
  'Is cursive just fancy printing?',
  'Are hammocks better than beds?',
  'Should you always RSVP?',
  'Is a ponytail a hairstyle or giving up?',
  'Are leftovers better the next day?',
  'Should you iron your clothes or embrace wrinkles?',
  'Is sleeping with socks on psychopathic?',
  'Are candles better than air fresheners?',
  'Should you fold or scrunch?',
  'Is a burrito a sandwich?',
  'Are Mondays actually the worst day?',
  'Should you butter all the way to the edge of the toast?',
  'Is soup a drink?',
  'Are stairs better than elevators?',
  'Should you wave back at someone waving at the person behind you?',
  'Is 72 degrees the perfect temperature?',
  'Are revolving doors a test of character?',
  'Should you eat the garnish?',
  'Is a quesadilla just a Mexican grilled cheese?',
  'Are naps better than coffee?',
  'Should you put your shopping cart back?',
];

// Fisher-Yates shuffle — exhausts all topics before repeating
let shuffled: string[] = [];
let shuffleIndex = 0;

function shuffle(arr: string[]): string[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

export function getNextTopic(): string {
  if (shuffleIndex >= shuffled.length) {
    shuffled = shuffle(TOPIC_POOL);
    shuffleIndex = 0;
  }
  return shuffled[shuffleIndex++];
}

export function getTopicPool(): string[] {
  return [...TOPIC_POOL];
}
